### ISSUE TITLE
When following instructions, daemonlog reports KeyError my_mqtt.returner_data (failed to add hook kind handler)

### ISSUE THREAD

**Issue by PeterGrace** [topeju/autopi_mqtt#2]
When following the instructions in the README, everything applies, but I get an error in daemon.log.  The error seems to indicate that something is set as handler instead of returner for my_mqtt.returner_data but as far as the autopi website configuration is concerned, I double checked all of the hooks and they say they are returners and not handlers.

Any thoughts?

```
Jan 15 12:04:22 autopi-914db119ab48 salt-minion[330]: [ERROR   ] Failed to add hook: {'kind': 'handler', 'name': 'my_mqtt', 'func': 'my_mqtt.returner_data'}
Jan 15 12:04:22 autopi-914db119ab48 salt-minion[330]: Traceback (most recent call last):
Jan 15 12:04:22 autopi-914db119ab48 salt-minion[330]:   File "/var/cache/salt/minion/extmods/utils/messaging.py", line 594, in init
Jan 15 12:04:22 autopi-914db119ab48 salt-minion[330]:     self.add_hook(hook["name"], hook["kind"], __salt__[hook["func"]], synchronize=hook.get("lock", False))
Jan 15 12:04:22 autopi-914db119ab48 salt-minion[330]:   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1117, in __getitem__
Jan 15 12:04:22 autopi-914db119ab48 salt-minion[330]:     func = super(LazyLoader, self).__getitem__(item)
Jan 15 12:04:22 autopi-914db119ab48 salt-minion[330]:   File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
Jan 15 12:04:22 autopi-914db119ab48 salt-minion[330]:     raise KeyError(key)
Jan 15 12:04:22 autopi-914db119ab48 salt-minion[330]: KeyError: 'my_mqtt.returner_data'
```

**Comment by topeju** [comment]
I saw some fairly similar behavior at some point (not necessarily quite the same, but also KeyErrors about the returner not being found). In my case, I found that just forcing the minion to restart often fixed this -- it might be that AutoPi is still using some old version (or a nonexistent version) of some of the custom code.

**Comment by PeterGrace** [comment]
@topeju  The error has subsided but I'm not actually getting any mqtt connections.,  I notice that I'm supposed to add my_mqtt_manager as custom code for a service, but in the services list, my_mqtt_manager has a red checkmark and there's no hooks, events, etc associated with it -- did I miss something in your README?

**Comment by PeterGrace** [comment]
I manually enabled the service but it was griping that `options["endpoint"] = settings["endpoint"]`  was a KeyError.  I tried copying the defaultEndpoint hash into the my_mqtt_manager code and setting options["endpoint"] equal to it, but that still did not kickstart any mqtt operations.

**Comment by topeju** [comment]
The Hooks tab on the my_mqtt_manager service should be empty, it should register the hooks automatically but they don't appear in the UI for some reason. You could try adding the hooks manually, but I don't know if this might cause further problems (in that case, you could try removing the `@edmp.register_hook` decorator calls from the handlers).

Oh, one thing I'd not documented: in the my_mqtt_manager service, you need to define a Worker to actually upload the data:
  * Name: upload
  * Start delay: 5 seconds (exact value shouldn't matter, probably, I just try to keep this from conflicting with the engine startup)
  * Interval: 1 sec (or as desired)
  * Loop: -1
  * Order: 1
  * Enabled: checked
  * Transactional: not checked
  * Kill on success: not checked
  * Suppress exceptions: checked
  * Auto start: checked
 
And add a Workflow for this Worker:
  * Handler: upload
  * Args: []
  * kwargs: {}
  * Converter: -
  * Trigger: -
  * Filter: -
  * Enricher: -
  * Returner: -

The README file is apparently missing instructions for the settings for the service -- I probably left these out from the README because I thought I'd removed the service settings from use altogether -- I had trouble using these, so the code *should* be using the endpoint configuration from the code rather than the service settings (but that line clearly tries to take the endpoint settings from the service). In any case, the service settings should be pretty much the same as the settings in the my_mqtt_cache code, i.e.:

    {
        "endpoint": {
            "client_id": "AutoPi",
            "clean_session": True,
            "userdata": None,
            "protocol": "MQTTv311",
            "transport": "tcp",
            "server": "mqtt.local",
            "port": 1883,
            "keepalive": 60,
            "bind_address": "",
            "topic_root": "AutoPi/",
            "qos": 2,
            "retain": False
        }
    }

Again, the contents of the settings in the service Settings tab shouldn't really matter, as the settings in the code should be used.

**Comment by topeju** [comment]
I pushed an update to the `my_mqtt_manager.py` to hopefully resolve the problem with accessing `settings["endpoint"]`, and to add documentation on what needs to be set up in the `my_mqtt_manager` service. Could you confirm whether these work for you?

**Comment by PeterGrace** [comment]
> Add new Workflow with:
Handler: upload
Args: []
kwargs: {}

I cannot do this step as upload doesn't show up as a handler for the workflows available.  Is there another missing piece?  No workflows show up in the drop down at all.

**Comment by topeju** [comment]
In that case, you will need to add the Hook manually first. The Hook for the upload handler should be:
  * Name: `upload`
  * Type: handler
  * Function: `my_mqtt_manager.upload_handler`
  * Enabled: checked
  * Args: `[]`
  * kwargs: `{}`

I must have had those hooks show up at some point (possibly by creating them as above), and now they just work even though my Hooks tab is also empty.

If there are problems creating the hooks, you should try to remove the `@edmp.register_hook` lines as mentioned above, but I don't know if this is needed.

**Comment by PeterGrace** [comment]
After adding the upload returner manually, it's working!  Nice.
